/**
  This is an automatically generated file. Changes to this file
  should instead either be made in a separate file or to the
  configuration CSV file used to generate this file, or to the template

  This file was mechanically generated by running the config.csv, containing
  comma-delimited key/value pairs of all configuration values through
  the "gen_config_maps.py" python script, which uses a cheetah template to
  mechanically format a valid C++ file.

  This file is packaged as a part of the FUMe project.

  To the extent possible under law, the person who associated CC0 with
  FUMe has waived all copyright and related or neighboring rights
  to FUMe.

  You should have received a copy of the CC0 legalcode along with this
  work.  If not, see http://creativecommons.org/publicdomain/zero/1.0/.
**/

// std
#include <utility>

// local public
#include "mc3msg.h"

// local private
#include "fume/configuration_maps.h"

using std::pair;
using std::begin;
using std::end;

namespace fume
{


static string_parm_map_t::value_type string_vals[] =
{
    { PEGASUS_OP_LIE3PLUS_NAME, "" },
    { PEGASUS_OP_SE2DPLUS_NAME, "" },
    { INITIATOR_NAME, "" },
    { LICENSE, "" },
    { UNKNOWN_VR_CODE, "UN" },
    { JPEG_2000_LOSSLESS_ONLY_SYNTAX, "1.2.840.10008.1.2.4.90" },
    { PEGASUS_OP_D2SEPLUS_NAME, "" },
    { JPEG_LOSSLESS_NON_HIER_14_SYNTAX, "1.2.840.10008.1.2.4.57" },
    { JPEG_SPEC_HIER_20_22_SYNTAX, "1.2.840.10008.1.2.4.61" },
    { DICTIONARY_FILE, "" },
    { JPIP_REFERENCED_DEFLATE_SYNTAX, "1.2.840.10008.1.2.4.95" },
    { COMPRESSION_RGB_TRANSFORM_FORMAT, "" },
    { IMPLEMENTATION_CLASS_UID, "5.4.216.8.539851.951" },
    { JPIP_REFERENCED_SYNTAX, "1.2.840.10008.1.2.4.94" },
    { JPEG_SPEC_NON_HIER_7_9_SYNTAX, "1.2.840.10008.1.2.4.54" },
    { IMPLICIT_LITTLE_ENDIAN_SYNTAX, "1.2.840.10008.1.2" },
    { PEGASUS_DISP_REGISTRATION, "" },
    { PEGASUS_OP_D2SEPLUS_REGISTRATION, "" },
    { PEGASUS_OP_LIE3PLUS_REGISTRATION, "" },
    { JPEG_EXTENDED_2_4_SYNTAX, "1.2.840.10008.1.2.4.51" },
    { LOG_FILE, "" },
    { PEGASUS_OP_SE2DPLUS_REGISTRATION, "" },
    { JPEG_LOSSLESS_HIER_14_SYNTAX, "1.2.840.10008.1.2.4.57" },
    { JPEG_LS_LOSSY_SYNTAX, "1.2.840.10008.1.2.4.81" },
    { PEGASUS_OP_J2KP_NAME, "" },
    { PEGASUS_OP_J2KE_NAME, "" },
    { MSG_INFO_FILE, "" },
    { JPEG_LOSSLESS_NON_HIER_15_SYNTAX, "1.2.840.10008.1.2.4.58" },
    { JPEG_FULL_PROG_HIER_25_27_SYNTAX, "1.2.840.10008.1.2.4.64" },
    { JPEG_FULL_PROG_HIER_24_26_SYNTAX, "1.2.840.10008.1.2.4.63" },
    { JPEG_SPEC_NON_HIER_6_8_SYNTAX, "1.2.840.10008.1.2.4.53" },
    { EXPLICIT_BIG_ENDIAN_SYNTAX, "1.2.840.10008.1.2.2" },
    { JPEG_SPEC_HIER_21_23_SYNTAX, "1.2.840.10008.1.2.4.62" },
    { JPEG_2000_MC_SYNTAX, "1.2.840.10008.1.2.4.93" },
    { JPEG_LS_LOSSLESS_SYNTAX, "1.2.840.10008.1.2.4.80" },
    { IP_TYPE, "" },
    { JPEG_LOSSLESS_HIER_28_SYNTAX, "1.2.840.10008.1.2.4.65" },
    { PRIVATE_SYNTAX_1_SYNTAX, "" },
    { JPEG_FULL_PROG_NON_HIER_11_13_SYNTAX, "1.2.840.10008.1.2.4.56" },
    { JPEG_FULL_PROG_NON_HIER_10_12_SYNTAX, "1.2.840.10008.1.2.4.55" },
    { PEGASUS_OP_JLSP_REGISTRATION, "" },
    { DECODER_TAG_FILTER, "" },
    { JPEG_EXTENDED_3_5_SYNTAX, "1.2.840.10008.1.2.4.52" },
    { PEGASUS_OP_J2KE_REGISTRATION, "" },
    { PEGASUS_OP_JLSP_NAME, "" },
    { ACCEPT_LIST_OF_APPLICATION_TITLES, "" },
    { PEGASUS_OP_LIP3PLUS_REGISTRATION, "" },
    { PRIVATE_SYNTAX_2_SYNTAX, "" },
    { LOCAL_APPL_CONTEXT_NAME, "" },
    { MPEG2_MPHL_SYNTAX, "1.2.840.10008.1.2.4.101" },
    { PEGASUS_OP_JLSE_NAME, "" },
    { JPEG_EXTENDED_HIER_16_18_SYNTAX, "1.2.840.10008.1.2.4.59" },
    { PEGASUS_OP_J2KP_REGISTRATION, "" },
    { JPEG_EXTENDED_HIER_17_19_SYNTAX, "1.2.840.10008.1.2.4.60" },
    { JPEG_2000_SYNTAX, "1.2.840.10008.1.2.4.91" },
    { JPEG_LOSSLESS_HIER_29_SYNTAX, "1.2.840.10008.1.2.4.66" },
    { PEGASUS_OP_JLSE_REGISTRATION, "" },
    { PEGASUS_OPCODE_PATH, "" },
    { DEFLATED_EXPLICIT_LITTLE_ENDIAN_SYNTAX, "1.2.840.10008.1.2.1.99" },
    { MPEG2_MPML_SYNTAX, "1.2.840.10008.1.2.4.100" },
    { CAPTURE_FILE, "" },
    { JPEG_2000_MC_LOSSLESS_ONLY_SYNTAX, "1.2.840.10008.1.2.4.92" },
    { IMPLICIT_BIG_ENDIAN_SYNTAX, "" },
    { MPEG4_AVC_H264_HP_LEVEL_4_1_SYNTAX, "1.2.840.10008.1.2.4.102" },
    { LARGE_DATA_STORE, "" },
    { TEMP_FILE_DIRECTORY, "" },
    { PEGASUS_OP_LIP3PLUS_NAME, "" },
    { EXPLICIT_LITTLE_ENDIAN_SYNTAX, "1.2.840.10008.1.2.1" },
    { DICTIONARY_ACCESS, "" },
    { IMPLEMENTATION_VERSION, "FUME_0_0_1" },
    { MPEG4_AVC_H264_BDC_HP_LEVEL_4_1_SYNTAX, "1.2.840.10008.1.2.4.103" },
    { NULL_TYPE3_VALIDATION, "" },
    { RECEIVER_NAME, "" },
    { RLE_SYNTAX, "1.2.840.10008.1.2.5" },
    { JPEG_BASELINE_SYNTAX, "1.2.840.10008.1.2.4.50" },
    { PEGASUS_DISP_REG_NAME, "" }
};




config_maps create_config_maps()
{
    config_maps ret;

    ret.strings.insert( begin(string_vals), end(string_vals) );




    return ret;
}

}
