#ifndef MCSTATUS_H
#define MCSTATUS_H
/** @file **/

/**
  This is an automatically generated file. Changes to this file
  should instead either be made in a separate file or to the
  data element CSV file used to generate this file

  This file was mechanically generated by running the mcstatus.csv file,
  containing a comma-delimited file of all status codes through the
  "gen_header.py" python script, which uses a cheetah template to mechanically
  format a valid C header. The status codes were obtained by running an original
  mcstatus.h through doxygen to obtain enum names and values. The descriptive
  text is an original work produced from reading public documentation on the API.

  This file is packaged as a part of the FUMe project.

  To the extent possible under law, the person who associated CC0 with
  FUMe has waived all copyright and related or neighboring rights
  to FUMe.

  You should have received a copy of the CC0 legalcode along with this
  work.  If not, see http://creativecommons.org/publicdomain/zero/1.0/.
**/

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef _WIN32
#define MCEXPORT __declspec(dllexport)
#else
#ifdef __GNUC__
#define MCEXPORT __attribute__((visibility("default")))
#else
#define MCEXPORT
#endif
#endif

typedef enum
{
    /** The operation completed successfully **/
    MC_NORMAL_COMPLETION = 1,
    /** The application entity title passed in as a parameter has already been registered **/
    MC_ALREADY_REGISTERED = 4000,
    /** The association was aborted **/
    MC_ASSOCIATION_ABORTED,
    /** The association was closed **/
    MC_ASSOCIATION_CLOSED,
    /** The association was rejected **/
    MC_ASSOCIATION_REJECTED,
    /** Cannot change value representation to SQ when attribute has value **/
    MC_ATTRIBUTE_HAS_VALUES,
    /** The buffer passed in as a parameter is too small for the output value **/
    MC_BUFFER_TOO_SMALL,
    /** The callback function returned an error **/
    MC_CALLBACK_CANNOT_COMPLY,
    /** The size returned from the callback function was negative **/
    MC_CALLBACK_DATA_SIZE_NEGATIVE,
    /** The size returned from the callback function was not even **/
    MC_CALLBACK_DATA_SIZE_UNEVEN,
    /** An output parameter returned from the callback function was invalid **/
    MC_CALLBACK_PARM_ERROR,
    /** The function cannot be called when a Callback Function is registered for the attribute **/
    MC_CALLBACK_REGISTERED,
    /** The function cannot perform the requested action **/
    MC_CANNOT_COMPLY,
    /** The profile file cannot be accessed **/
    MC_CANT_ACCESS_PROFILE,
    /** An error occurred while accessing configuration information **/
    MC_CONFIG_INFO_ERROR,
    /** Required configuration information could not be found **/
    MC_CONFIG_INFO_MISSING,
    /** An error occurred while accessing the data dictionary **/
    MC_DDFILE_ERROR,
    /** The message failed validation **/
    MC_DOES_NOT_VALIDATE,
    /** The attribute does not have an assigned value **/
    MC_EMPTY_VALUE,
    /** The function completed but there is still more data? **/
    MC_END_OF_DATA,
    /** No extended negotiation information was received **/
    MC_EXT_INFO_UNAVAILABLE,
    /** ? **/
    MC_FOUND,
    /** ? **/
    MC_FUNCTION_UNAVAILABLE,
    /** This function cannot be called on a VR of this type **/
    MC_INCOMPATIBLE_VR,
    /** This value cannot be assigned to this VR **/
    MC_INCOMPATIBLE_VALUE,
    /** The application ID passed in as a parameter is invalid **/
    MC_INVALID_APPLICATION_ID,
    /** The application title passed in as a parameter is invalid **/
    MC_INVALID_APPLICATION_TITLE,
    /** The association ID passed in as a parameter is invalid **/
    MC_INVALID_ASSOC_ID,
    /** The string passed in as a parameter contains invalid characters for this value representation **/
    MC_INVALID_CHARS_IN_VALUE,
    /** The command passed in as a parameter is invalid **/
    MC_INVALID_COMMAND,
    /** The data type passed in as a paramter is invalid **/
    MC_INVALID_DATA_TYPE,
    /** No more elements are present in the list **/
    MC_END_OF_LIST,
    /** The group number passed in as a parameter is invalid **/
    MC_INVALID_GROUP,
    /** The host name passed in as a parameter is invalid **/
    MC_INVALID_HOST_NAME,
    /** The item ID passed in as a parameter is invalid **/
    MC_INVALID_ITEM_ID,
    /** The application entity title passed in as a parameter has an invalid length **/
    MC_INVALID_LENGTH_FOR_TITLE,
    /** The value passed in as a parameter has an invalid length for this value representation **/
    MC_INVALID_LENGTH_FOR_VR,
    /** Unused **/
    MC_INVALID_LICENSE,
    /** The Message ID passed in as a parameter is invalid **/
    MC_INVALID_MESSAGE_ID,
    /** An invalid message was received **/
    MC_INVALID_MESSAGE_RECEIVED,
    /** The configuration value name passed in as a parameter is invalid **/
    MC_INVALID_PARAMETER_NAME,
    /** The port number passed in as a parameter is invalid **/
    MC_INVALID_PORT_NUMBER,
    /** The private code passed in as a parameter is invalid **/
    MC_INVALID_PRIVATE_CODE,
    /** The service list passed in as a parameter is invalid **/
    MC_INVALID_SERVICE_LIST_NAME,
    /** The tag passed in as a parameter is invalid **/
    MC_INVALID_TAG,
    /** The transfer syntax passed in as a parameter is invalid **/
    MC_INVALID_TRANSFER_SYNTAX,
    /** The value passed in as a parameter is not valid for the value representation **/
    MC_INVALID_VALUE_FOR_VR,
    /** The value number passed in as a parameter is not valid for the tag **/
    MC_INVALID_VALUE_NUMBER,
    /** The VR code passed in as a parameter is invalid **/
    MC_INVALID_VR_CODE,
    /** The log is empty **/
    MC_LOG_EMPTY,
    /** The message contains no attributes **/
    MC_MESSAGE_EMPTY,
    /** The object validated successfully **/
    MC_MESSAGE_VALIDATES,
    /** A required configuration parameter is missing **/
    MC_MISSING_CONFIG_PARM,
    /** An error occurred while accessing the message configuration file **/
    MC_MSGFILE_ERROR,
    /** The value passed in as a parameter must be positive **/
    MC_MUST_BE_POSITIVE,
    /** The network connection was shut down **/
    MC_NETWORK_SHUT_DOWN,
    /** An application entity title has not been registered **/
    MC_NO_APPLICATIONS_REGISTERED,
    /** ? **/
    MC_NO_CALLBACK,
    /** There is no function available to check a conditional attribute **/
    MC_NO_CONDITION_FUNCTION,
    /** There is no filesystem present on this system and no configuration functions specified **/
    MC_NO_FILE_SYSTEM,
    /** Extended negotiation information has not been registered **/
    MC_NO_INFO_REGISTERED,
    /** Unused **/
    MC_NO_LICENSE,
    /** The merge.ini file cannot be found **/
    MC_NO_MERGE_INI,
    /** No more attributes are present in the message **/
    MC_NO_MORE_ATTRIBUTES,
    /** No more values are present in the attribute **/
    MC_NO_MORE_VALUES,
    /** ? **/
    MC_NO_PROFILE,
    /** There are no association requests pending **/
    MC_NO_REQUEST_PENDING,
    /** The attribute is invalid for the specified message/service **/
    MC_NON_SERVICE_ATTRIBUTE,
    /** The requested data could not be found **/
    MC_NOT_FOUND,
    /** The value is not in the list of valid enumerated values **/
    MC_NOT_ONE_OF_ENUMERATED_VALUES,
    /** The value is not in the list of valid defined terms **/
    MC_NOT_ONE_OF_DEFINED_TERMS,
    /** The value passed in as a parameter is NULL **/
    MC_NULL_POINTER_PARM,
    /** The attribute value is NULL **/
    MC_NULL_VALUE,
    /** ? **/
    MC_PROTOCOL_ERROR,
    /** An attribute required for this message is missing **/
    MC_REQUIRED_ATTRIBUTE_MISSING,
    /** ? **/
    MC_REQUIRED_DATASET_MISSING,
    /** A value required for this attribute is missing **/
    MC_REQUIRED_VALUE_MISSING,
    /** The requested operation is not valid for the current state of the association **/
    MC_STATE_VIOLATION,
    /** A signal interupted the system call **/
    MC_SYSTEM_CALL_INTERRUPTED,
    /** An unexpected error has occurred **/
    MC_SYSTEM_ERROR,
    /** The attribute passed in as a parameter already exists in the message **/
    MC_TAG_ALREADY_EXISTS,
    /** An error occurred while accessing a temporary file **/
    MC_TEMP_FILE_ERROR,
    /** The specified operation timed out **/
    MC_TIMEOUT,
    /** The attribute has too few values **/
    MC_TOO_FEW_VALUES,
    /** The group has too many private blocks **/
    MC_TOO_MANY_BLOCKS,
    /** The attribute has too many values **/
    MC_TOO_MANY_VALUES,
    /** It is not possible to check the condition for a conditional attribute **/
    MC_UNABLE_TO_CHECK_CONDITION,
    /** The message being sent uses a service which was not negoatiated **/
    MC_UNACCEPTABLE_SERVICE,
    /** Not all data has been received **/
    MC_UNEXPECTED_EOD,
    /** ? **/
    MC_UNKNOWN_ITEM,
    /** The service list passed in as a parameter has not been registered **/
    MC_UNKNOWN_SERVICE,
    /** The attribute may not have a NULL value **/
    MC_VALUE_MAY_NOT_BE_NULL,
    /** The attribute may not hava a value **/
    MC_VALUE_NOT_ALLOWED,
    /** The value passed in as a parameter is out of range **/
    MC_VALUE_OUT_OF_RANGE,
    /** The value passed in as a parameter is too large for its value representation **/
    MC_VALUE_TOO_LARGE,
    /** The value representation for the specified attribute is already valid **/
    MC_VR_ALREADY_VALID,
    /** The library is already initialized **/
    MC_LIBRARY_ALREADY_INITIALIZED,
    /** The library has not been initialized **/
    MC_LIBRARY_NOT_INITIALIZED,
    /** A record offset value is invalid **/
    MC_INVALID_DIRECTORY_RECORD_OFFSET,
    /** The file ID passed in as a parameter is invalid **/
    MC_INVALID_FILE_ID,
    /** The DICOMDIR ID passed in as a parameter is invalid **/
    MC_INVALID_DICOMDIR_ID,
    /** The entity ID passed in as a parameter is invalid **/
    MC_INVALID_ENTITY_ID,
    /** The MRDR ID passed in as a parameter is invalid **/
    MC_INVALID_MRDR_ID,
    /** The requested Item ID cannot be retrieved **/
    MC_UNABLE_TO_GET_ITEM_ID,
    /** The file padding passed in as a parameter is invalid for the file size **/
    MC_INVALID_PAD,
    /** ? **/
    MC_ENTITY_ALREADY_EXISTS,
    /** The child directory record is invalid for its parent type **/
    MC_INVALID_LOWER_DIR_RECORD,
    /** The directory record type is invalid **/
    MC_BAD_DIR_RECORD_TYPE,
    /** ? **/
    MC_UNKNOWN_HOST_CONNECTED,
    /** A timeout occurred while trying to read a message **/
    MC_INACTIVITY_TIMEOUT,
    /** The SOP class UID passed in as a parameter is invalid **/
    MC_INVALID_SOP_CLASS_UID,
    /** ? **/
    MC_INVALID_VERSION,
    /** A tag was not written in ascending order **/
    MC_OUT_OF_ORDER_TAG,
    /** The TCP network connection failed **/
    MC_CONNECTION_FAILED,
    /** A network device with the specified hostname could not be found **/
    MC_UKNOWN_HOST_NAME,
    /** ? **/
    MC_INVALID_FILE,
    /** The association was aborted **/
    MC_NEGOTIATION_ABORTED,
    /** The SR ID passed in as a parameter is invalid **/
    MC_INVALID_SR_ID,
    /** The specified SR ID cannot be retrieved **/
    MC_UNABLE_TO_GET_SR_ID,
    /** A service with the specified name already exists **/
    MC_DUPLICATE_NAME,
    /** A transfer syntax with the specified name already exists **/
    MC_DUPLICATE_SYNTAX,
    /** ? **/
    MC_EMPTY_LIST,
    /** ? **/
    MC_MISSING_NAME,
    /** The service name passed in as a parameter is invalid **/
    MC_INVALID_SERVICE_NAME,
    /** The service being freed is currently in use **/
    MC_SERVICE_IN_USE,
    /** ? **/
    MC_NO_CONTEXT,
    /** ? **/
    MC_OFFSET_TABLE_TOO_SHORT,
    /** ? **/
    MC_MISSING_DELIMITER,
    /** An error occurred while compressing/decompressing the data **/
    MC_COMPRESSION_FAILURE,
    /** The function completed but there are still more frames **/
    MC_END_OF_FRAME,
    /** ? **/
    MC_MUST_CONTINUE_BEFORE_READING,
    /** A compressor is required for the message **/
    MC_COMPRESSOR_REQUIRED,
    /** A decompressor is required for the message **/
    MC_DECOMPRESSOR_REQUIRED,
    /** ? **/
    MC_DATA_AVAILABLE,
    /** ? **/
    MC_ZLIB_ERROR,
    /** ? **/
    MC_NOT_META_SOP,
    /** ? **/
    MC_INVALID_ITEM_TRANSFER_SYNTAX,
    /** Unused **/
    MC_LICENSE_ERROR,
    /** The maximum number of operation requests has been reached **/
    MC_MAX_OPERATIONS_EXCEEDED,
    /** The Record ID passed in as a parameter is invalid **/
    MC_INVALID_RECORD_ID,
    /** The DICOMDIR file is invalid **/
    MC_INVALID_DICOMDIR_FILE,
    /** ? **/
    MC_INVALID_VR
} MC_STATUS;

#ifdef __cplusplus
}
#endif

#endif // MCSTATUS_H
