<?xml version="1.0" encoding="UTF-8"?>
<!--
  This file is packaged as a part of the FUMe project.

  To the extent possible under law, the person who associated CC0 with
  FUMe has waived all copyright and related or neighboring rights
  to FUMe.

  You should have received a copy of the CC0 legalcode along with this
  work.  If not, see http://creativecommons.org/publicdomain/zero/1.0/.
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:db="http://docbook.org/ns/docbook"
                xmlns:fn="http://www.w3.org/2005/xpath-functions"
                exclude-result-prefixes="db fn" >

    <xsl:output method="xml" encoding="UTF-8" indent="yes"
/>

<!-- This XSLT file Fills in the "Include" nodes generated by the iod_to_xml.xslt
     script with the table definitions filled generated by the macro_to_xml.xslt
     script
-->

<xsl:strip-space elements="*"/>

<xsl:template match="node()|@*">
     <xsl:copy>
       <xsl:apply-templates select="node()|@*"/>
     </xsl:copy>
 </xsl:template>

<xsl:template match="Sequence">
    <xsl:copy>
      <xsl:apply-templates select="@*" />
    </xsl:copy>
</xsl:template>

 <xsl:template match="Include">
    <xsl:variable as="xs:string" name="link_id" select="@ID"/>
    <xsl:if test="count(document('macros.xml')//Macro[@ID = string($link_id)]/*) = 0">
    <Error ID="{$link_id}" />
    </xsl:if>
    <xsl:apply-templates select="document('macros.xml')//Macro[@ID = string($link_id)]/*" />
</xsl:template>

</xsl:stylesheet>
