<?xml version="1.0" encoding="UTF-8"?>
<!--
  This file is packaged as a part of the FUMe project.

  To the extent possible under law, the person who associated CC0 with
  FUMe has waived all copyright and related or neighboring rights
  to FUMe.

  You should have received a copy of the CC0 legalcode along with this
  work.  If not, see http://creativecommons.org/publicdomain/zero/1.0/.
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:db="http://docbook.org/ns/docbook"
                xmlns:fn="http://www.w3.org/2005/xpath-functions"
                exclude-result-prefixes="db fn" >

    <xsl:output method="xml" encoding="UTF-8" indent="yes"
/>

<!-- This XSLT file expands the "Include" nodes generated by the module_to_xml
     XSLT file. PS3.3's macro and module definitions frequenly have "include"
     statements which indicate that another section of the standard is to be
     "included" in the macro or module definition. This function expands these
     definitions as is required to generate the final item/IOD definitions.
-->

<xsl:strip-space elements="*"/>

<xsl:template match="node()|@*">
     <xsl:copy>
       <xsl:apply-templates select="node()|@*"/>
     </xsl:copy>
 </xsl:template>

 <xsl:template match="Include">
    <xsl:variable as="xs:string" name="my_link_id" select="ancestor::Macro/@ID"/>
    <xsl:variable as="xs:string" name="link_id" select="@ID"/>
    <xsl:if test="$my_link_id != $link_id">
        <xsl:if test="count(//Macro[@ID = string($link_id)]/*) = 0">
            <xsl:value-of select="error('No Matching Macro Node')" />
        </xsl:if>
        <xsl:apply-templates select="//Macro[@ID = string($link_id)]/*"/>
    </xsl:if>
    <xsl:if test="$my_link_id = $link_id">
        <SelfReference ID="{$my_link_id}" />
    </xsl:if>
</xsl:template>

</xsl:stylesheet>
